Databases:
    SqlServer:
        Server: localhost\SQLEXPRESS
        Port: 1433 #default
        Database: demo_exam
        IntegratedSecurity: true
        UserName: null
        Password: null
        TrustedConnection: true
        TrustServerCertificate: true
        ConnectionTimeout: 00:00:15 #default
        MaxPoolSize: 100 #default