Databases:
    SqlServer:
        Server: localhost\SQLEXPRESS
        #Port: 1433
        Database: Online_Store
        IntegratedSecurity: true
        UserName: null
        Password: null
        TrustedConnection: true
        TrustServerCertificate: true
        ConnectionTimeout: 00:00:15
        MaxPoolSize: 100

Cache:
    Path: C:\Users\рс\AppData\Local\Temp\OnlineStore.Cache\User
    ReadOnly: true